# =============================================================================
# UPGIT Config
# =============================================================================

# default uploader id
default_uploader = "github"
# default_uploader = "gitee"

# The file name formatting template was uploaded
#   / The directory separator is used to distinguish directories
#   {year} Year, for example: 2022
#   {month} Month, for example: 02
#   {day} Day, for example: 01
#   {unix_ts} Time stamp, for example: 1643617626
#   {fname} Original file name, such as logo (without suffix)
#   {fname_hash} MD5 hash value of {fname}
#   {ext} File name suffix, for example: .png
#   The following example generates a file name preview: 2022/01/upgit_20220131_1643617626.png
# rename = "{year}/{month}/upgit_{year}{month}{day}_{unix_ts}{ext}"
rename = "{year}_{month}/{unix_ts}{ext}"

# -----------------------------------------------------------------------------
# Custom extra output formats
# -----------------------------------------------------------------------------
#   {url} direct URL of the file
[output_formats]
"bbcode" = "[img]{url}[/img]"
"html" = '<img src="{url}" />'
"markdown-simple" = "![]({url})"

# -----------------------------------------------------------------------------
# URL replacing rules. RawUrl -[replace]-> Url
# -----------------------------------------------------------------------------

# If your network access to Github is abnormal or sluggish, you can try the following CDN acceleration.
# [replacements]
# "raw.githubusercontent.com" = "cdn.jsdelivr.net/gh"
# "/master" = "@master"

# =============================================================================
# Configurations examples for some uploaders, leave them blank if not used
# =============================================================================

# Github uploader
[uploaders.github]
# Branch to save files, for example master or main
branch = "master"

# "pat" enter the Github token that has the "repo" permission
# Get token from https://github.com/settings/tokens
pat = "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"

# The name of your public Github repository
# Attention: In order for you and others to access image resources, your Github repository must be public.
#            In private repositories Github blocks unauthorized requests and you will get a 404.
repo = "image-assets"

# your Github username  
username = "volving"


# Gitee
[uploaders.gitee]
username = "volving"
repo = "image-assets"
# https://gitee.com/profile/personal_access_tokens/new
access_token = "e09e7f37967a0afeaa555856baf1bb91"

